cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

coupons/urls.py
from . import views
from django.urls import path

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='coupon_apply'),]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('store.urls', namespace='store')),
    path('accounts/', include ('accounts.urls', namespace='accounts')),
    path('cart/', include ('cart.urls', namespace='cart')),
    path('orders/', include ('orders.urls', namespace='orders')),
    path('coupons/', include ('coupons.urls', namespace='coupons')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES=[{i,str(i)} for i in range (1,51)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES , coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id, status='AV')

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product , quantity= cd['quantity'] , override_quantity= cd['override'])
        return redirect('cart:cart_details')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id, status='AV')
    cart.delete(product)
    return redirect('cart:cart_details')

def cart_details(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form']=CartAddProductForm(initial={'quantity':item['quantity'],
                                                                 'override':True})
    context = { 'cart':cart, 'coupon_apply_form':CouponApplyForm}
    return render(request , 'cart/cart_details.html',context)

templates/cart/cart_details.html
{% extends 'base.html' %}

{% block content %}
<section class="cart_section layout_padding">
    <div class="container">
        <div class="heading_container heading_center">
            <h2>
                Shopping Cart
            </h2><br><br>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="cart_items">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                                <th scope="col">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                            {% with product=item.product %}
                            <tr>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img src="{{product.image.url}}" alt="Product Name" class="img-fluid"
                                            style="width: 50px; height: 50px; object-fit: cover; margin-right: 10px;">
                                        {{product.name}}
                                    </div>
                                </td>
                                <td>${{item.price}}</td>
                                <td>
                                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                        {% csrf_token %}
                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.override }}
                                        <input type="submit" value="Update" class="btn btn-warning">
                                    </form>

                                </td>
                                <td>{{item.total_price}}</td>
                                <td>
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="submit" value="Remove" class="btn btn-danger">
                                    </form>
                                </td>
                            </tr>
                            {% endwith %}
                            {% endfor %}

                    </table>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart_summary">
                    <h4>Cart Summary</h4>
                    <ul>
                        <li>Tax: <span>$30</span></li>
                        <li>Total: <span>{{cart.get_total_price}}</span></li>
                    </ul>
                    {% if cart.coupon %}
                    <ul>
                        <li>
                            Subtotal:
                            <span>${{ cart.get_total_price|floatformat:".2" }}</span>
                        </li>
                        <li>
                            Discount:
                            <span>
                                {{ cart.coupon.code }} coupon ({{ cart.coupon.discount }}%)
                            </span>
                        </li>
                        <li style="color: green;">
                            Discount Amount:
                            <span>$ {{ cart.get_discount|floatformat:".2" }}</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            Total After Discount:
                            <span><b>$ {{ cart.get_total_price_after_discount|floatformat:".2" }}</b></span>
                        </li>
                    </ul>
                    {% endif %}

                    <form class="coupon_form mt-4" action="{% url 'coupons:coupon_apply' %}" method="post">
                        {% csrf_token %}
                        {{ coupon_apply_form }}
                        <!-- <input type="text" id="coupon_code" class="form-control" placeholder="Enter your code"> -->
                        <button type="submit" class="btn btn-primary mt-2">Apply Coupon</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- end cart section -->

<!-- info section -->
<section class="info_section ">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="info_contact">
                    <h5>
                        <a href="" class="navbar-brand">
                            <span>
                                Minics
                            </span>
                        </a>
                    </h5>
                    <p>
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        Address
                    </p>
                    <p>
                        <i class="fa fa-phone" aria-hidden="true"></i>
                        +01 1234567890
                    </p>
                    <p>
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        demo@gmail.com
                    </p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="info_info">
                    <h5>
                        Information
                    </h5>
                    <p>
                        Eligendi sunt, provident, debitis nemo, facilis cupiditate velit libero dolorum aperiam enim
                        nulla iste maxime corrupti ad illo libero minus.
                    </p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="info_links">
                    <h5>
                        Useful Link
                    </h5>
                    <ul>
                        <li>
                            <a href="index.html">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="about.html">
                                About
                            </a>
                        </li>
                        <li>
                            <a href="product.html">
                                Products
                            </a>
                        </li>
                        <li>
                            <a href="why.html">
                                Why Us
                            </a>
                        </li>
                        <li>
                            <a href="testimonial.html">
                                Testimonial
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="info_form ">
                    <h5>
                        Newsletter
                    </h5>
                    <form action="">
                        <input type="email" placeholder="Enter your email">
                        <button>
                            Subscribe
                        </button>
                    </form>
                    <div class="social_box">
                        <a href="">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-youtube" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}