accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', views.user_signUp, name='sign_up'),
    path('login/', views.user_login, name='login'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', views.logout, name='logout'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),


]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('store.urls', namespace='store')),
    path('accounts/', include ('accounts.urls', namespace='accounts')),
    path('cart/', include ('cart.urls', namespace='cart')),
    path('orders/', include ('orders.urls', namespace='orders')),
    path('coupons/', include ('coupons.urls', namespace='coupons')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser
import pycountry

class MyAccountManager(BaseUserManager):
    
    def create_user(self, email,first_name, last_name,username, country='',password=None):
        if not email:
            raise ValueError('User must have an email address.')
        if not username:
            raise ValueError('User must have a username.')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            username=username,
            country=country,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            password=password
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    @staticmethod
    def get_country():
        countries = list(pycountry.countries)
        country_choices = [(country.alpha_2, country.name) for country in countries]
        return country_choices

    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    email = models.EmailField(max_length=100, unique=True)
    username = models.CharField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)
    country = models.CharField(max_length=2, choices=get_country(), default='US')

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS =['first_name','last_name','username']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django import forms
from .models import Account
    
class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})
    )

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'country','phone_number']

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        print(cleaned_data)
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Your passwords don\'t match!')
        print(cleaned_data)
        return cleaned_data
    

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs['placeholder']= 'Enter First Name'
            
        self.fields['last_name'].widget.attrs['placeholder']= 'Enter Last Name'

        self.fields['phone_number'].widget.attrs['placeholder']= 'Enter Phone Number'
        
        self.fields['email'].widget.attrs['placeholder']= 'Enter Email'

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import RegisterForm
from .models import Account
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.decorators import login_required 


def user_signUp(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            country = form.cleaned_data['country']
            user_name = email.split("@")[0]
            password = form.cleaned_data['password']
            phone_number= form.cleaned_data['phone_number']

            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                country=country,
                username=user_name,
                password=password
            )
            user.phone_number=phone_number
            user.save()
            current_site = get_current_site(request)
            subject= 'Please Activate Your Email'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email=email
            email = EmailMessage(
                subject=subject,
                body=message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to=[to_email]
            )
            email.send()

            return redirect(reverse('accounts:login') + f'?command=verification&email={to_email}')
    else:
        form = RegisterForm()
    
    context = {'form': form,}

    return render(request, 'accounts/register.html', context)



def user_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(email=email, password=password)
        if user is not None:
            auth_login(request, user)
            messages.success(request, 'You are logged in.')
        else:
            messages.error(request, 'Invalid login! Email or password is invalid.')
            return redirect('accounts:login')

    return render(request, 'accounts/login.html')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is activated.')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid activation link or the link has expired.')
        return redirect('accounts:sign_up')


@login_required(login_url='accounts:login')
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        messages.success(request, 'You are logged out now.')
        return redirect('accounts:login')
    return render(request, 'accounts/logout.html')

templates/accounts/account_verification_email.html
{% autoescape off %}


Hi {{user.first_name}},
Please click on blue link to confirm your registration.
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, Please ignore this email.


{% endautoescape %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% if request.GET.command == 'verification' %}
<br><br><br>
<div class="row justify-content-center">
    <div class="alert alert-success">
        <h4 class="alert header">Well done!</h4>
        <p>Thank you for signing up! We’ve sent a verification email to <b>{{ request.GET.email }}</b>. Please verify
            it.</p>

        <hr class="border-green-400 my-2">
        <p>Already Verified? <a href="{% url 'accounts:login' %}">Log in</a></p>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6"><br><br><br>
            <h2 class="text-center my-4">Login </h2>
             {% include 'includes/alerts.html' %}
            <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label>Email:</label>
                    <input type="email" class="form-control" name="email" placeholder="Email" required>
                </div>
                <div class="form-group">
                    <label>Password:</label>
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <br>
            <p> Don't have an account? <a href="{% url 'accounts:sign_up' %}">Register</a></p>

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">

<body>
    <div class="container">
        <div class="logout-box">
            <h2>Are you sure you want to log out?</h2>
            <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Yes, Log me out</button>
                <a href="{% url 'base' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</body>
</html>

templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="cll-md-6 clo-lg-4">
            <h2 class="text-center my-4"> Register </h2>

            <form method="POST">
                {% csrf_token %}
                {{ form |crispy }}
                <br>
                <button type="submit" class="btn btn-outline-dark ">Register</button>
            </form>
            <br>
            <p>Have an account? <a href="{% url 'accounts:login' %}">Login</a></p>

        </div>
        <br>

    </div>
</div>
{% endblock %}