cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('store.urls', namespace='store')),
    path('accounts/', include ('accounts.urls', namespace='accounts')),
    path('cart/', include ('cart.urls', namespace='cart')),
    path('orders/', include ('orders.urls', namespace='orders')),
    path('coupons/', include ('coupons.urls', namespace='coupons')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='list_of_products'),
    path('category/<slug:category_slug>', views.product_list, name='products_by_category'),
    path('product/<slug:product_slug>', views.product_details, name='product_details'),
    path('search/', views.product_search, name='product_search'),
]

templates/includes/alerts.html
<div class="message-container text-center">
    {% if messages %}
        {% for message in messages %}
            <div id="message" class="container">
                <div {% if message.tags %}class="alert alert-{{ message.tags }}"{% endif %} role="alert">
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                    <h5><b>{{ message }}</b></h5>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>



<script>

    $(document).ready(function(){
        setTimeout(function(){
            $('.container').fadeOut('slow');
        }, 3000);
    });
</script>

templates/includes/navbar.html
<header class="header_section">
  <div class="header_top">
    <div class="container-fluid">
      <div class="top_nav_container">
        <div class="contact_nav">
          <a href="">
            <i class="fa fa-phone" aria-hidden="true"></i>
            <span>
              Call : +01 123455678990
            </span>
          </a>
          <a href="">
            <i class="fa fa-envelope" aria-hidden="true"></i>
            <span>
              Email : demo@gmail.com
            </span>
          </a>
        </div>
        <form class="search_form" method="get" action="{% url 'store:product_search' %}">
          <input type="text" name="query" class="form-control" placeholder="Search here...">
          <button class="" type="submit">
            <i class="fa fa-search" aria-hidden="true"></i>
          </button>
        </form>
        <div class="user_option_box">
          <a href="" class="account-link">
            <i class="fa fa-user" aria-hidden="true"></i>
            <span>
              My Account
            </span>
          </a>
          <a href="{% url 'cart:cart_details' %}" class="cart-link">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <span>
              Cart
            </span>
            <span> {% with total_items=cart|length %}

              {% if total_items > 0 %}
              <small><a href=" {% url 'cart:cart_details' %}"> {{total_items}} items ,
                  {{cart.get_total_price}} $
                </a> </small>
              {% else %}
              <small> Your Cart is Empty</small>
              {% endif %}
              {% endwith %}

            </span>
          </a>
        </div>
      </div>

    </div>
  </div>
  <div class="header_bottom">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="index.html">
          <span>
            E-commerce
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ">
            <li class="nav-item active">
              <a class="nav-link" href="index.html">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for x in categories %}
                <a class="dropdown-item" href="{% url 'store:products_by_category' x.slug %}">{{x.name}}</a>
                {% endfor %}
              </div>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="about.html"> About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="product.html">Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="why.html">Why Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="testimonial.html">Testimonial</a>
            </li>

          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>