cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('store.urls', namespace='store')),
    path('accounts/', include ('accounts.urls', namespace='accounts')),
    path('cart/', include ('cart.urls', namespace='cart')),
    path('orders/', include ('orders.urls', namespace='orders')),
    path('coupons/', include ('coupons.urls', namespace='coupons')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='list_of_products'),
    path('category/<slug:category_slug>', views.product_list, name='products_by_category'),
    path('product/<slug:product_slug>', views.product_details, name='product_details'),
    path('search/', views.product_search, name='product_search'),
]

store/models.py
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        
    def __str__(self):
        return self.name

    def save(self, *args ,**kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)     
    

class Product(models.Model):
    STATUS = (
        ('DF', 'Draft'),
        ('AV', 'Available'),
    )
    name = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='products/images')
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=6 , decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, max_length=2, default='AV')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes= [models.Index(fields=['id','slug'])]
        verbose_name = "Product"
        verbose_name_plural = "Products"
        

    def __str__(self):
        return self.name

    def save(self, *args ,**kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)     
    

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product,Category
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank
from cart.forms import CartAddProductForm
from django.core.cache import cache
from django.core.paginator import Paginator


def product_list(request, category_slug=None):
    products=Product.objects.filter(status='AV')
    categories = Category.objects.all()
    category = None
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products =  products.filter(category=category)
    paginator = Paginator(products, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number) 
    context = {
        'products': products,
        'category ': category,
        'categories': categories ,
        'page_obj': page_obj,
    }
    
    return render(request, 'store/product_list.html', context)




def product_details(request, product_slug):
    cache_key = f'product_{product_slug}'
    product=cache.get(cache_key)
    if product is None:
        product = get_object_or_404(Product, slug=product_slug,status='AV' )
        cache.set(cache_key,product,timeout = 60 * 30 )

    cart_product_form= CartAddProductForm()
    context = {'detail': product,
               'cart_product_form':cart_product_form,
               }
    
    return render(request, 'store/product_details.html', context)


def product_search(request):
    query = None
    results = []

    if 'query' in request.GET:
        query = request.GET.get('query')
        search_vector = SearchVector('name', 'description')
        search_query = SearchQuery(query)

        if query:
            results = Product.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=query, status='AV').order_by('-rank')

    context = {
        'query': query,
        'results': results,
    }

    return render(request, 'store/search.html', context)

templates/store/product_details.html
{% extends 'base.html' %}

{% block content %}
<!-- product details section -->
<section class="product_details_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Product Details
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="img-box">
            <img src="{{detail.image.url}}" alt="Product Name" class="img-fluid">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <h4>{{detail.name}}</h4>
            <h5>
              <span>$</span> {{detail.price}}
            </h5>
            <p>
             {{detail.description}}
            </p>
            <div class="star_container">
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star-half-o" aria-hidden="true"></i>
            </div>
            <form method="post" action="{% url 'cart:cart_add' detail.id %}">
             {{cart_product_form}}
             {% csrf_token %}
             <input type="submit" value="Add to Cart" class="btn btn-primary">

            </form>
          </div>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-md-12">
          <h4>Additional Information</h4>
          <ul>
            <li>Feature 1: Description of the feature.</li>
            <li>Feature 2: Description of the feature.</li>
            <li>Feature 3: Description of the feature.</li>
            <li>Feature 4: Description of the feature.</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}

templates/store/product_list.html
{% extends 'base.html' %}

{% block content %}

<section class="slider_section ">
    <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container ">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="detail-box">
                                <h1>
                                    Welcome to our shop
                                </h1>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quam velit saepe
                                    dolorem deserunt quo quidem ad optio.
                                </p>
                                <a href="">
                                    Read More
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="img-box">
                                <img src="images/slider-img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container ">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="detail-box">
                                <h1>
                                    Welcome to our shop
                                </h1>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quam velit saepe
                                    dolorem deserunt quo quidem ad optio.
                                </p>
                                <a href="">
                                    Read More
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="img-box">
                                <img src="images/slider-img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container ">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="detail-box">
                                <h1>
                                    Welcome to our shop
                                </h1>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quam velit saepe
                                    dolorem deserunt quo quidem ad optio.
                                </p>
                                <a href="">
                                    Read More
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="img-box">
                                <img src="images/slider-img.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel_btn_box">
            <a class="carousel-control-prev" href="#customCarousel1" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#customCarousel1" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>
</div>

<section class="product_section layout_padding">
    <div class="container">
        <div class="heading_container heading_center">
            <h2>
                Our Products
            </h2>
        </div>
        <div class="row">
            {% for product in products %}
            <div class="col-sm-6 col-lg-4">
                <div class="box">
                    <div class="img-box">
                        <img src="{{product.image.url}}" alt="">
                    </div>
                    <div class="detail-box">

                        <h5>
                            <a href="{% url 'store:product_details' product.slug %}" class="href"> {{product.name}}</a>

                        </h5>
                        <div class="product_info">
                            <h5>
                                <span>$</span> {{product.price}}
                            </h5>
                            <div class="star_container">
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                                <i class="fa fa-star" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="paginator">
            {% if page_obj.has_previous %}
                <a href="?page=1" >First</a>
                <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
            
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
        
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        </div>
        

</section>

<section class="about_section">
    <div class="container-fluid  ">
        <div class="row">
            <div class="col-md-5 ml-auto">
                <div class="detail-box pr-md-3">
                    <div class="heading_container">
                        <h2>
                            We Provide Best For You
                        </h2>
                    </div>
                    <p>
                        Totam architecto rem beatae veniam, cum officiis adipisci soluta perspiciatis ipsa, expedita
                        maiores quae accusantium. Animi veniam aperiam, necessitatibus mollitia ipsum id optio ipsa odio
                        ab facilis sit labore officia!
                        Repellat expedita, deserunt eum soluta rem culpa. Aut, necessitatibus cumque. Voluptas
                        consequuntur vitae aperiam animi sint earum, ex unde cupiditate, molestias dolore quos quas
                        possimus eveniet facilis magnam? Vero, dicta.
                    </p>
                    <a href="">
                        Read More
                    </a>
                </div>
            </div>
            <div class="col-md-6 px-0">
                <div class="img-box">
                    <img src="images/about-img.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/store/search.html
{% extends 'base.html' %}

{% block content %}

{% if query %}
    <h1> Search with '{{ query }}'</h1>
    <br>
    {% with results.count as total_results %}
        <p>Found {{ total_results }}</p>
    {% endwith %}
{% endif %}

{% for product in results %}
    <h4>
        <a href="{% url 'store:product_details' product.slug %}">
            {{ product.name }}
        </a>
    </h4>
{% empty %}
    <p> There are no results for your '{{ query }}'</p>
{% endfor %}

{% endblock %}